#!/bin/bash

options=(
   style=round
   width=6.0
   hidpi=off
   active_color=0xff00b7eb   # Electric light blue (fully opaque)
   inactive_color=0xc0e0ffff # Very light cyan with transparency
   blur_radius=5
)

borders "${options[@]}"
